[package]
name = "ts-bindgen-macro"
version = "0.1.0"
description = "Generate a wasm-bindgen interface from a typescript interface."
authors = ["Adam Berger <adam@ratchetdesigns.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
ts-bindgen-gen = { version = "0.1.0", path = "../ts-bindgen-gen" }
quote = "1.0"
syn = "1.0.74"

[dev-dependencies]
trybuild = "1.0.25"
